SqlServerに接続

diff --git a/tutorial/lesson/dotnet/dotnetcore22/Vagrantfile b/tutorial/lesson/dotnet/dotnetcore22/Vagrantfile
--- a/tutorial/lesson/dotnet/dotnetcore22/Vagrantfile
+++ b/tutorial/lesson/dotnet/dotnetcore22/Vagrantfile
@@ -1,6 +1,6 @@
 # ansibleインストール用shell
 $ansible_install = <<SHELL
-  if ! type virtualenv > /dev/null 2>&1; then
+  if ! type /usr/local/bin/virtualenv > /dev/null 2>&1; then
     # rootユーザとして実行されるためsudo不要
     # yum install -y https://centos7.iuscommunity.org/ius-release.rpm
     # yum search python37
@@ -27,6 +27,9 @@ SHELL
 Vagrant.configure("2") do |config|
   config.vm.box = "bento/centos-7.6"
   config.vm.box_version = "201812.27.0"
+
+  config.vm.network "private_network", ip: "192.168.50.11"
+
   config.vm.provider "virtualbox" do |vm|
     # メモリを設定
     vm.memory = 4092
@@ -35,10 +38,20 @@ Vagrant.configure("2") do |config|
 
     vm.customize [ "modifyvm", :id, "--cpus", "2", "--ioapic", "on"]
 
-    # Vagrant assumes that this means the command failed! setup となったときに、vagrant-vbguestが悪さをしていたらfalseにする
-    # config.vbguest.auto_update = false
+    # 普段はtrue。Vagrant assumes that this means the command failed! setup となったときに、falseにしてみる。解決した場合、vagrant-vbguestが悪さをしている
+    config.vbguest.auto_update = false
   end
-
-    # ansibleをインストール
-    config.vm.provision "shell", inline: $ansible_install
+  # ansible vaultのためにパーミッションを指定
+  config.vm.synced_folder "./provision", "/provision", id: "ansible", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=664"]
+  # ansibleをインストール
+  config.vm.provision "shell", inline: $ansible_install
+  # ansibleを実行
+  config.vm.provision "shell", inline: <<-SHELL
+    # timezoneを日本に変更
+    timedatectl set-timezone Asia/Tokyo
+    # virtualenv起動
+    source /home/vagrant/venv/bin/activate
+    # provision 実行
+    DEFAULT_VAULT_PASSWORD_FILE=ANSIBLE_CONFIG=/provision/.ansible.cfg ansible-playbook -i /provision/playbooks/inventory/hosts /provision/playbooks/play.yml -c local -v --vault-password-file /provision/playbooks/.passwd
+  SHELL
 end
